# ---- Stage 1: build frontend ----
FROM node:20-alpine AS builder

WORKDIR /usr/src/app

COPY frontend ./frontend
COPY shared ./shared

WORKDIR /usr/src/app/frontend

RUN npm install
RUN npm run build

# ---- Stage 2: nginx ----
FROM nginx:alpine

COPY nginx.conf  /etc/nginx/conf.d/default.conf

COPY --from=builder /usr/src/app/frontend/dist /usr/share/nginx/html/

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]