services:
  app:
    build: .
    env_file:
      - .env.prod
    container_name: my_discord_app
    ports: 
      - "3000:3000"
    volumes:
      - /usr/src/app/node_modules
    depends_on:
      - db
      - redis_db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: my_discord_frontend
    ports: 
      - "80:80"
  db: 
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root 
      POSTGRES_DB: mydisdb     
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  
  redis_db:
    image: redis:7-alpine
    container_name: my_dis_app_redis
    ports: 
      - "6379:6379"
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio:latest
    container_name: my_dis_app_minio
    ports: 
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data
volumes:
  db_data:
  redis_data: